"""Add cascade delete relationships

Revision ID: 1a31ce608336
Revises: d98dd8ec85a3
Create Date: 2024-07-31 22:24:34.447891

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1a31ce608336'
down_revision = 'd98dd8ec85a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if item table exists to be safe
    tables = inspector.get_table_names()
    if 'item' not in tables:
        return

    op.alter_column('item', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
               
    fks = [fk['name'] for fk in inspector.get_foreign_keys('item')]
    if 'item_owner_id_fkey' in fks:
        op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
        # Only create the new one if we dropped the old one? 
        # Or should we check if a cascade one exists? 
        # Hard to check delete rule via inspector easily in one line without iterating.
        # Assuming if we dropped the old one, we need the new one.
        op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    else:
        # If the specific named FK is gone, assumes it's already migrated or manual intervention.
        # We could try to detect if ANY FK on owner_id exists.
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'])
    op.alter_column('item', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
