"""Add app_slug

Revision ID: 7beecfbb883d
Revises: a1b2c3d4e5f6
Create Date: 2026-02-12 10:16:41.701912

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7beecfbb883d'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_apitoken_user_id', table_name='apitoken')
    # op.drop_table('apitoken')
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('remote_server')]

    if 'app_slug' not in columns:
        op.add_column('remote_server', sa.Column('app_slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remote_server', 'app_slug')
    # op.create_table('apitoken', ...) # skipped
    # ### end Alembic commands ###
    op.create_table('apitoken',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('request_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='apitoken_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='apitoken_pkey'),
    sa.UniqueConstraint('token', name='apitoken_token_key')
    )
    op.create_index('ix_apitoken_user_id', 'apitoken', ['user_id'], unique=False)
    # ### end Alembic commands ###
