"""add_aws_and_provisioning_jobs

Revision ID: cccf54b9dc9e
Revises: b207bfc0f9a9
Create Date: 2026-02-07 09:28:56.571685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cccf54b9dc9e'
down_revision = 'b207bfc0f9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('remote_server', sa.Column('hosting_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='docker'))
    op.add_column('remote_server', sa.Column('aws_instance_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('remote_server', sa.Column('aws_instance_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('remote_server', sa.Column('aws_region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('remote_server', sa.Column('aws_ami_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('remote_server', sa.Column('aws_key_pair_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('remote_server', sa.Column('aws_public_ip', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('remote_server', sa.Column('aws_security_group_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remote_server', 'aws_security_group_id')
    op.drop_column('remote_server', 'aws_public_ip')
    op.drop_column('remote_server', 'aws_key_pair_name')
    op.drop_column('remote_server', 'aws_ami_id')
    op.drop_column('remote_server', 'aws_region')
    op.drop_column('remote_server', 'aws_instance_type')
    op.drop_column('remote_server', 'aws_instance_id')
    op.drop_column('remote_server', 'hosting_provider')
    op.drop_table('provisioning_job')
    # ### end Alembic commands ###
